### ISSUE TITLE
Great to see DDD specs in Javascript form.

### ISSUE THREAD

**Issue by john-arcus** [acanimal/node-specification-pattern#1]
I am a big fan of DDD and the spec classes. I have implemented many in PHP and am pleased to see how you have implemented them beautifully in this project. Thanks.

I am currently starting to learn Google Apps and was wondering if your project is easy to reuse in [Google Apps Libraries](https://developers.google.com/apps-script/guides/libraries). I know very little of Javascript and Google Apps and so am trying to think of ways to resuse code and store business rules in a Single Place of Truth so that the same rule can be used in, say, a Spreadsheet column validation as well as a script that, say, iterates through a batch of Sheets in a folder to test well-formedness.

Have you ever heard of your project being used in such cases?

Thanks once again.

**Comment by acanimal** [comment]
@john-arcus you can use/copy or whatever with the code :) 
Never used Apps Libraries, but I think there should be no problem if you copy&paste the code in a common "library" and you upload to Apps Library.

**Comment by john-arcus** [comment]
Thanks for the speedy response.

I shall investigate and let you know the result.
